apiVersion: v1
kind: Pod
metadata:
  name: ready-if-service-ready
  namespace: gulzat-task1
spec:
  containers:
    - name: readyone
      image: nginx:1.16.1-alpine
      ports:
        - containerPort: 8080
      livenessProbe:
        exec:
          command: ["true"]
        initialDelaySeconds: 1
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 2
      readinessProbe:
        exec:
          command:
            - wget
            - -T2
            - -O-
            - http://service-am-i-ready:80
      initialDelaySeconds: 1
      periodSeconds: 5
